### ISSUE TITLE
Here seems Wrong

### ISSUE THREAD

**Issue by freesunshine0316** [HarderThenHarder/transformers_tasks#15]
https://github.com/HarderThenHarder/transformers_tasks/blob/adbfce276f1a139d3764c83eeb87bace3bf11e3e/RLHF/model.py#L97

**Comment by HarderThenHarder** [comment]
Hi, what I want to do here is to maximize the sum of (good_sentence_reward - bad_sentence_reward). I'm not sure which  mistake you pointed out, could you give me some more details please?

**Comment by freesunshine0316** [comment]
People usually minimize -log p

**Comment by yaleimeng** [comment]
@freesunshine0316  will  you please pull  a  requeest with your code  according to your understanding about this ?

**Comment by freesunshine0316** [comment]
Unfortunately I don't have time to do this right now.

**Comment by HarderThenHarder** [comment]
Hi, I checked paper and found it uses `-log p`:

![image](https://user-images.githubusercontent.com/36854507/219573293-ed13f024-31b0-43bc-bd3e-bcdf520aefe7.png)

**I have fix this problem.** The only thing I did is to switch [sigmoid loss](https://github.com/HarderThenHarder/transformers_tasks/blob/adbfce276f1a139d3764c83eeb87bace3bf11e3e/RLHF/model.py#L96) to logsigmoid loss. 

Since `log loss` can scale loss(e.g. 0.4 -> -0.916) , model can learn more faster than `no log` loss. 

Here is my comparative experiment: 

![image](https://user-images.githubusercontent.com/36854507/219574647-233db7f2-d6b7-4de1-9025-fa6805714e82.png)
![image](https://user-images.githubusercontent.com/36854507/219574703-e7c8ff8b-ac12-4ba2-bfa1-5c39c66614bf.png)

 thanks for your correction ^~^
